typofix
git-svn-id: http://www.varnish-cache.org/svn/trunk/varnish-cache@5514 d4fa192b-c00b-0410-8231-f00ffab90ce4

diff --git a/redhat/varnish_reload_vcl b/redhat/varnish_reload_vcl
--- a/redhat/varnish_reload_vcl
+++ b/redhat/varnish_reload_vcl
@@ -45,7 +45,7 @@ if [ ! "$RELOAD_VCL" = "1" ]; then
 	exit 2
 
 elif [ -z "$VARNISH_VCL_CONF" ]; then
-	echo "Error: VARNISH_VCL_CONF" is not set
+	echo "Error: VARNISH_VCL_CONF is not set"
 	exit 2
 
 elif [ ! -s "$VARNISH_VCL_CONF" ]; then
@@ -82,7 +82,7 @@ if $VARNISHADM vcl.list > /dev/null; then
 	$debug && echo vcl.list succeeded
 else
 	echo "Unable to run $VARNISHADM vcl.list"
-	exit 2
+	exit 1
 fi
 
 if $VARNISHADM vcl.list | awk ' { print $3 } ' | grep -q $new_config; then
@@ -99,7 +99,6 @@ echo "Using new config name $new_config"
 if $VARNISHADM vcl.load $new_config $VARNISH_VCL_CONF; then
 	$debug && echo "$VARNISHADM vcl.load succeded"
 else
-	retval=$?
 	echo "$VARNISHADM vcl.load failed"
 	exit 1
 fi
